### ISSUE TITLE
preserving current querystring in pager

### ISSUE THREAD

**Issue by ddddddddeee22211** [sgjsakura/AspNetCore#11]
Hello,
Thanks for the wonderful package you made for the community.
My question is regarding the pager taghelper as  I use it in views with filtering(search) and sorting handled bt GET request. I read the demo and inspected the source code to find a way to preserve currentSearch and currentSort in pagers links. In the current package all querystring parameters are lost in the newly generated pages links.
example
this is how my view URL looks like 
localhost/Products/?searchName=notebook&searchStatus=InStock&sort=Quantity_Desc
however in pager all links are like
localhost/Products/?page=1
localhost/Products/?page=2
(so all current search and sort are lost)
also i checked all-route-data but i could not find a solution because i want to append whats ever parameter included in URL to pager links

this article has one old implementation for pager if you can check or find a better one
[http://www.itworld.com/article/2956575/development/how-to-sort-search-and-paginate-tables-in-asp-net-mvc-5.html](url)
and this one made it generic without magicstrings (More practical)
[https://codeutil.wordpress.com/2013/04/10/list-sort-edit-filter-in-asp-net-mvc-4/
](url)

one suggestion to PagerDemo.md
if you append this (FirstOrDefault) as many developers are not aware of to generate headers name in pagedlist

``<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().ProductCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().ProductName)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>            
        </tr>
}
    </tbody>
</table>``

**Comment by sgjsakura** [comment]
HI, thank you for your feedback and suggestion.

Unforetunately, I cannot reproduce your scene due to lack of inforamtion. Defaultly the QueryNamePageItemLinkGenereator will preserve all query arguments and it should satisfy your requirement. Could you provide more information about how you use the pager tag and how you configrure the pager options?

Best wishs,

**Comment by ddddddddeee22211** [comment]
I checked again and found that pager is behaving correctly and preserve all the values
my mistake was trying to achieve the same behavior with Anchor tag helper 
therefore I confused myself in code
your package works wonderfully and perfectly and does not have any issue at all
