### ISSUE TITLE
Query string with spaces issue

### ISSUE THREAD

**Issue by PezCo** [sgjsakura/AspNetCore#12]
In version 2 of PagedList pager helper. Spaces in a existing query string are being encoded incorrectly. e.g

V1 **Works fine**
Category=All%20Categories&page=4
becomes Category=All Categories&page=4

V2 **Does not work**
Category=All%20Categories&page=4
becomes Category=All%252520Categories&page=4

**Comment by sgjsakura** [comment]
@PezCo Thank you for your feedback, this is a confirmed bug and it has been fixed in the lastest 2.0.9 version. 

If you have any new question, please feel free to reopen it or submit a new issue :-)
