### ISSUE TITLE
Adding additional attributes to the Pager

### ISSUE THREAD

**Issue by gbfromhb** [sgjsakura/AspNetCore#14]
Thanks for all the hard work. I'm just not understanding I think. It looks like I should be able to add some additional tags to the the pager links, example: asp-route-customerId=3. I have several I want to add in the controller or in the top of the view for the first time the page is created with no existing query string items. It looks like once they are there all is good, If this is possible how could I do this? Thanks in advance.

**Comment by sgjsakura** [comment]
@gbfromhb Hi, if you want to customize the generated URL , e.g. by adding new arguments, you may change the link generator to use a `Custom` method override. The following code shows a example:

```HTML
<pager item-default-link='PagerItemLinkGenerators.Custom((int page) => Url.Action("Index,", "Home, {page = page, id = myId}))' />
```

Hope it helps and best wishes :-)

**Comment by gbfromhb** [comment]
That can work. Is there an overload or by using settings that would enable me to not set the Controller or Action, and just add a dictionary of additional query string items and it uses the previous Controller and Action? 

One more thing I needed to put new right in from of the first scawiggly bracket {

`<pager item-default-link='PagerItemLinkGenerators.Custom((int page) => Url.Action("Index,", "Home", new {page = page, id = myId}))' />`

Thanks again.

**Comment by gbfromhb** [comment]
i dropped in a Dictionary<string, string> with the following data.

[0]	{[sortOrder, ]}
[1]	{[currentFilter, ]}
[2]	{[searchBy, ]}
[3]	{[page, 1]}
[4]	{[pageSize, 20]}
[5]	{[id, 3]}
[6]	{[customerId, 3]}
[7]	{[returnProjectList, CustomerId:3]}

Here is how I dropped it in:
<pager generation-mode="ListOnly" item-default-link='PagerItemLinkGenerators.Custom((int page) => Url.Action("Index,", "ProjectListView", pageState.GetPagerSettings()))'  />

This is the link that was created.
/ProjectListView/Index,?Comparer=System.Collections.Generic.GenericEqualityComparer%601%5BSystem.String%5D&Count=8&Keys=sortOrder&Keys=currentFilter&Keys=searchBy&Keys=page&Keys=pageSize&Keys=id&Keys=customerId&Keys=returnProjectList&Values=1&Values=20&Values=3&Values=3&Values=CustomerId%3A3`

Could there be a different way, thanks.

**Comment by gbfromhb** [comment]
I did the following:
`<pager generation-mode="ListOnly" item-default-link='PagerItemLinkGenerators.Custom((int page) => Url.Action("Index,", "ProjectListView", pageState.GetPagerSettings()))'  />`

It passed a Dictionary<string,string> with 7 key value pairs, and this is was the link that was created. 

/ProjectListView/Index,?Comparer=System.Collections.Generic.GenericEqualityComparer%601%5BSystem.String%5D&Count=8&Keys=sortOrder&Keys=currentFilter&Keys=searchBy&Keys=page&Keys=pageSize&Keys=id&Keys=customerId&Keys=returnProjectList&Values=1&Values=20&Values=3&Values=3&Values=CustomerId%3A3
 
Any other ideas? Thanks  for your time.

**Comment by sgjsakura** [comment]
@gbfromhb Hi, thank you for your feedback. The `Url.Action` methods are provided by ASP.NET MVC Core and not related with the pager system. `PagerItemLinkGenerators.Custom` method just execute the delegate and get the string which will be used as the link address.

It seems there's an override version that statify your method which is `UrlHelperExtensions.RouteUrl(Microsoft.AspNetCore.Mvc.IUrlHelper, object)`. For usage and documentation for this method, you may see the ASP.NET official documentation library.

Hope it helps :-)

**Comment by gbfromhb** [comment]
Thank you very much for the info, greatly appreciated.

**Comment by gbfromhb** [comment]
Worked Brilliantly. I don't know if anyone is interested, but here was my solution. Take this down or move it if it is to much up here.
    
         using Microsoft.AspNetCore.Routing;
         using System.Collections.Generic;
         
         namespace HubAction.Web.Tools {
            public class PageState {
            public int? CustomerId { get; set; }
            public int? PartnerId { get; set; }
            public int? ProjectMarketId { get; set; }
            public int? ActivationLocationId { get; set; }
            public int? ActivationId { get; set; }
            public string ReturnCustomer { get; set; }
            public string ReturnProjectMarket { get; set; }
            public string ReturnProjectList { get; set; }
            public string ReturnLocation { get; set; }
            public string SortOrder { get; set; }
            public string CurrentFilter { get; set; }
            public string SearchBy { get; set; }
            public int? Page { get; set; }
            public int? PageSize { get; set; }
         
            public RouteValueDictionary GetRouteValues(string routeKey = null, string routeValue = null, RouteValueDictionary routeParams = null) {

               RouteValueDictionary routeDict = new RouteValueDictionary(new {
                  sortOrder = !string.IsNullOrEmpty(SortOrder) ? SortOrder : string.Empty,
                  currentFilter = !string.IsNullOrEmpty(CurrentFilter) ? CurrentFilter : string.Empty,
                  searchBy = !string.IsNullOrEmpty(SearchBy) ? SearchBy : string.Empty,
                  page = Page.HasValue ? Page.Value.ToString() : string.Empty,
                  pageSize = PageSize.HasValue ? PageSize.Value.ToString() : string.Empty
               });

               if(CustomerId.HasValue) {
                  routeDict.Add("customerId", CustomerId.Value.ToString());
               }

               if(ProjectMarketId.HasValue) {
                  routeDict.Add("projectMarketId", ProjectMarketId.Value.ToString());
               }

               if(ActivationLocationId.HasValue) {
                  routeDict.Add("activationLocationId", ActivationLocationId.Value.ToString());
               }

               if(ActivationId.HasValue) {
                  routeDict.Add("activationId", ActivationId.Value.ToString());
               }

               if(!string.IsNullOrWhiteSpace(ReturnCustomer)) {
                  routeDict.Add("returnCustomer", ReturnCustomer);
               }

               if(!string.IsNullOrWhiteSpace(ReturnProjectMarket)) {
                  routeDict.Add("returnProjectMarket", ReturnProjectMarket);
               }

               if(!string.IsNullOrWhiteSpace(ReturnProjectList)) {
                  routeDict.Add("returnProjectList", ReturnProjectList);
               }

               if(!string.IsNullOrWhiteSpace(ReturnLocation)) {
                  routeDict.Add("returnLocatoin", ReturnLocation);
               }

               if(!string.IsNullOrEmpty(routeKey) && !string.IsNullOrEmpty(routeValue)) {
                  if(routeDict.ContainsKey(routeKey)) {
                     routeDict[routeKey] = routeValue;
                  } else {
                     routeDict.Add(routeKey, routeValue);
                 }
              }

               if(routeParams != null) {
                  foreach(KeyValuePair<string, object> kvp in routeParams) {
                     if(kvp.Value == null) continue;

                     if(routeDict.ContainsKey(kvp.Key)) {
                        routeDict[kvp.Key] = kvp.Value.ToString();
                     } else {
                        routeDict.Add(kvp.Key, kvp.Value.ToString());
                     }
                  }
               }
               return routeDict;
            }
         }
      }

Here is the pager on the View.
`<pager generation-mode="ListOnly" item-default-link='PagerItemLinkGenerators.Custom((int page) => Url.RouteUrl(pageState.GetRouteValues("page", page.ToString())))' />`

And here was the result for the link of one of the buttons, yes the page number was correct for each of the page number buttons.

/ProjectListView/Index/3?page=2&pageSize=20&customerId=3

Thanks for everything.

**Comment by sgjsakura** [comment]
Thank you for sharing your code to all others. It seems that this issue has been sloved. Closing this issue. Please feel free to reopen it or create new issues if you have any new problem.
