### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by SKAT-Krd** [sgjsakura/AspNetCore#17]
![screenshot_1](https://cloud.githubusercontent.com/assets/22500416/21472930/fc5bbeee-cb00-11e6-897a-25cdbad73605.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/22500416/21472932/2c09f2be-cb01-11e6-8b5b-0ea87037dc03.png)

**Comment by sgjsakura** [comment]
@SKAT-Krd Hi, thank you for your feedback, and could you provide a minimum project to reproduce this issue?

Thank you and waiting for your reply :-)

**Comment by SKAT-Krd** [comment]
Thanks It works. A new problem. Do not change the active page.
![screenshot_1](https://cloud.githubusercontent.com/assets/22500416/21479179/346247b0-cb63-11e6-81f3-0becb819ba69.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/22500416/21479180/34626812-cb63-11e6-9be1-82b7714d5108.png)

**Comment by SKAT-Krd** [comment]
@sgjsakura Thank you. It works perfectly.
