### ISSUE TITLE
PagerItemLinkGenerators not in the current context

### ISSUE THREAD

**Issue by sylvaincaillot** [sgjsakura/AspNetCore#18]
Hello, 
I need to rewrite the pager link as I am using partial views and it doesn't point to the correct module. I read in the tutorial that I would need to use PagerItemLinkGenerators such as 
`<pager source="Model.StaffResults"  item-default-link='PagerItemLinkGenerators.Format...`
but i get a "The name PagerItemLinkGenerators does not exist in the current context".

I have added the following in the appsettings.json:
```
,
  "Pager": {
    "ExpandPageItemsForCurrentPage": 2,
    "PageItemsForEnding": 3,
    "Layout": "Default",
    "AdditionalSettings": {
      "my-setting-one": "1"
    },

    "ItemOptions": {
      "Default": {
        "Content": "TextFormat:{0}",
        "Link": "QueryName:page"
        "InactiveBehavior": "Hide",
        "ActiveMode": "Always"
      },
      "GoToLastPage": {
        "Content": "Text:Go To Last Page"
      }
    }
  }
```
, added in my view.cshtml:
`@addTagHelper *, Sakura.AspNetCore.Mvc.PagedList`

 and already added in the startup.cs:
`services.Configure<PagerOptions>(Configuration.GetSection("Pager")`);

What do i need to add to make it worked. I am currently using the v2.0.11.

Thanks

Sylvain

**Comment by sgjsakura** [comment]
@sylvaincaillot Hi, thank you for your feedback. The `PagerItemLinkGenerators` is a class defined in `Sakura.AspNetCore.Mvc` namespace. Would you make a double check that the namespace is currently used, or you may using full name `Sakura.AspNetCore.Mvc.PagerItemLinkGenertors`.
