### ISSUE TITLE
PagedList.Async dependencies

### ISSUE THREAD

**Issue by hey-red** [sgjsakura/AspNetCore#19]
Hi. Currently PagedList.Async depends on PagedList 2.0.0, not 2.0.1
You can update this?

**Comment by sgjsakura** [comment]
@hey-red Hi, thank you for your reply. Actually, the dependency for nuget packages are normally forward compatible, which means you can use any version 2.x.x as its dependency package. 


I'll update this package with lastest dependencies in the next update. In your current case, you may manually add the veresion `2.0.1` of `Sakura.AspNetCore.PagedList` to your `project.json` and use `dotnet restore` to reload the neweset package if you want use new features in the newer version. If these steps still not works, please tell me.

Thank you and waiting for your kind reply :-)

**Comment by hey-red** [comment]
Yep, i'm already make it :) Thx.
