### ISSUE TITLE
Checked attribute assignment in FlagsEnumInputTagHelper.cs

### ISSUE THREAD

**Issue by cyberyak** [sgjsakura/AspNetCore#20]
`// Set checked attribute	
if (EnumFlagValue.HasFlag((Enum) EnumFlagFor.Model))
			{
				output.Attributes.SetAttribute("checked", "checked");
			}`

This check should work opposite way: 
`// Set checked attribute
			if (EnumFlagFor.Model != null && ((Enum)EnumFlagFor.Model).HasFlag(EnumFlagValue))
            {
                output.Attributes.SetAttribute("checked", "checked");
            }`

**Comment by sgjsakura** [comment]
HI, thank you for your feedback, and this bug has been fixed in the lastest 1.2.2 version. I'm closing this issue since it has been solved. Please feel free to reopen it if you have any new quesion.
