### ISSUE TITLE
Simple pager usage issue

### ISSUE THREAD

**Issue by MukthaP** [sgjsakura/AspNetCore#27]
I have made all the required changes as per the guidance for simple usage of pager.
But seems like it does not consider the page number I click on instead considers the default one.
Can you please help me with this?

**Comment by sgjsakura** [comment]
@MukthaP Hi, thank you for your feedback and could you provide your code and screen snapshots?

Thank you again and wait for your kind reply.

**Comment by sgjsakura** [comment]
Since the author of this issue has no reply for days, I'm closing it. Please feel free to reopen it if you have any new question.
