### ISSUE TITLE
Custom paging parameters cannot be obtained

### ISSUE THREAD

**Issue by yujiajunbmj** [sgjsakura/AspNetCore#31]
page
<pager setting-tagname="C#" />
global
public void ConfigureServices(IServiceCollection services) { services.AddBootstrapPagerGenerator(options => { // Use default pager options. options.ConfigureDefault(); }); }
action
`public IActionResult DataPager(string tagname,int page)
{

} `
The tagname does not get the parameter value
I don't know if I have any other configuration wrong?
Thank you for your reply.

**Comment by sgjsakura** [comment]
I'm closing this issue since it is duplicated with #30 .
