### ISSUE TITLE
FlagsEnumModelBinderProvider does not work in .NET Core 2.1

### ISSUE THREAD

**Issue by bmforce** [sgjsakura/AspNetCore#32]
.NET Core 2.1 has a new class EnumTypeModelBinderProvider. FlagsEnumModelBinderProvider must be inserted before it. Otherwise, the **Enum** types do not reach the GetBinder method.

**Comment by sgjsakura** [comment]
Thank you for your feedback and this problem is fixed in the version 1.3.8. I'm closing this issue and please feel free to reopen it if you have any new question.
