### ISSUE TITLE
【Document】The document is not up to date

### ISSUE THREAD

**Issue by snowchenlei** [sgjsakura/AspNetCore#33]
EnumTypeSelectTagHelper.cs Does not support `<select asp-enum-type="@typeof(ProjectAccessType)" name="AccessType"></select>`，throw Exception“The object reference is not set to the object instance”。
Look at the source code `asp-enum-value` no set，But I don't want to set the default value。hope add isnull(EnumValueAttributeName)。
Finally, keep the document up to date。Thank you!
EnumTypeSelectTagHelper.cs现已不支持`<select asp-enum-type="@typeof(ProjectAccessType)" name="AccessType"></select>`方式，会出现“未将对象引用设置到对象实例”错误。
看源码发现是`asp-enum-value`未设置，但是我不想要设置默认值。希望可以对EnumValueAttributeName增加null判断，并更新下文档，
最后，请保持文档是最新的。谢谢!

**Comment by sgjsakura** [comment]
HI, sorry for the delay response. This problem is confirmed and I will fix it as soon as possible.

**Comment by snowchenlei** [comment]
thank you

**Comment by sgjsakura** [comment]
Hi, this problem is fixed in the package with version 1.3.9 and I'm now closing this issue. Please feel free to reopen it if you encounter any new problem.

**Comment by snowchenlei** [comment]
OnNo, items.First(i => i.Value == selectedValue).Selected = true; throw Exception "Sequence contains no matching element" in EnumTypeSelectTagHelper class
