### ISSUE TITLE
Where is the "source" attribute in "pager" tag? ASP.NET Core 3.0

### ISSUE THREAD

**Issue by SalehGladius** [sgjsakura/AspNetCore#38]
After migrating to ASP.NET Core 3.0, the `pager` tag doesn't recognize the `source` attribute!

```html
     <pager source="@Model.Users" generation-mode="ListOnly" />

**Comment by sgjsakura** [comment]
Hi, this problem is caused during the updating of the project structure and the `source` attribute is broken. It is now fixed in the lastest version. I'm closing this issue and please feel free to reopen it if you have any new problem.
