### ISSUE TITLE
TotalPage Maybe 0

### ISSUE THREAD

**Issue by suningnet** [sgjsakura/AspNetCore#40]
Hi
totalPage Maybe 0 if get none record.please don't throw this exception.

`      if (this.TotalPage <= 0)
        throw new InvalidOperationException("The value of 'total-page' attribute must be positive integer.");
      if (this.CurrentPage <= 0 || this.CurrentPage > this.TotalPage)
        throw new InvalidOperationException("The value of 'current-page' attribute must between 1 and the value of 'total-page' attribute.");`

**Comment by sgjsakura** [comment]
Hi, this problem is fixed in the lastest version 3.0.2. I'm closing this issue and please feel free to reopen it if you meet any new problem.
