### ISSUE TITLE
ToPagedList method is not available

### ISSUE THREAD

**Issue by dileepar** [sgjsakura/AspNetCore#9]
I was trying to call ToPagedList() on a List object. But it seems the method is not available in the Sakura.AspNetCore namespace. In resharper is shows in red color. Can some one guide me to solve the matter ?

Thanks.

**Comment by dileepar** [comment]
Sorry it was my mistake. I didn't install sakura.aspnetcore.pagedlist package.

**Comment by sgjsakura** [comment]
Pelease feel free to reopen it if you have any new problem :-)

**Comment by dileepar** [comment]
Thank you. Is there anyway to remove ?page=1 query string from the [1] button. So the page is redirect to the home page when user clicks [1] page.

**Comment by sgjsakura** [comment]
@dileepar Currently the numbered pager items are all use the same template, thus it is a bit complex to custom them invididually. For your target, you may use a custom link generator  (ItemLinkGenrators.Custom) to fully control the link generation process for each button. 

While, it is easy to set a custom link for special buttons (e.g. go to first page button). 

I'll try to make custom setting for each numbered items easier in the next version. Thank you:-)
